# Generated by Django 4.1.3 on 2022-11-10 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20221105_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='numbr_in_stock',
            new_name='number_in_stock',
        ),
    ]
